sudo: false
language: java
jdk:
- oraclejdk7
env:
  global:
  - "DITA_OT_VERSION=2.2.2"
before_script:
- ".travis/install.sh"
script:
- ".travis/publish.sh"
after_success:
- ".travis/deploy.sh"
branches:
  only:
  - develop
