sudo: false
language: java
jdk:
- oraclejdk7
env:
  global:
  - DITA_OT_VERSION=2.2.2
before_install:
- openssl aes-256-cbc -K $encrypted_324699cc92df_key -iv $encrypted_324699cc92df_iv
  -in .travis/ditaotbot_rsa.enc -out .travis/ditaotbot_rsa -d
install:
- ".travis/install.sh"
script:
- ".travis/publish.sh"
after_success:
- ".travis/deploy.sh"
branches:
  only:
  - develop
